n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print('A soma vale {}'.format(n1+n2))
print('A divisão vale {}'.format(n1-n2))
print('A multiplicação vale {}'.format(n1*n2))
print('A divisão vale {}'.format(n1/n2))
print('A divisão intera vale {}'.format(n1//n2))
print('O módulo vale {}'.format(n1 % n2))
print('A exponenciação vale {}'.format(n1**n2))
