print('=======DESAFIO 08=======')
n = float(input('Digite um valor (m) para saber a sua conversão em cm e mm: '))
print('>> {}km\n>> {}hm\n>> {}dam'.format(n/1000, n/100, n/10))
print('>> {}m'.format(n))
print('>> {}dm\n>> {}cm\n>> {}mm'.format(n*10, n*100, n*1000))
