print('=======DESAFIO 04=======')
n = input('Digite qualquer coisa: ')
print('==========DADOS=========')
print('Seu tipo primitivo é - {}'.format(type(n)))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um número? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Está em maiúscula? {}'.format(n.isupper()))
print('Está em minúscula? {}'.format(n.islower()))
print('Está capitalizado? {}'.format(n.istitle()))
